# Generated by Django 3.1.7 on 2021-07-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210515_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Necksize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Necksize',
                'ordering': ('ordering',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='accept_alteration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='alteration_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='necksize',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.necksize'),
        ),
    ]
