# Generated by Django 3.1.7 on 2021-07-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_product_accept_alteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accept_alteration',
            field=models.BooleanField(default=False),
        ),
    ]
