# Generated by Django 3.1.7 on 2021-07-16 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_accept_alteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='necksize',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.necksize'),
        ),
    ]
