# Generated by Django 3.1.7 on 2021-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210715_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hip_size',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Normal'), (2, 'Medium'), (3, 'Large')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neck_size',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Normal'), (2, 'Medium'), (3, 'Large')], default=0),
        ),
    ]
