# Generated by Django 3.1.7 on 2021-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210715_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hip_size',
        ),
        migrations.AlterField(
            model_name='profile',
            name='neck_size',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
