# Generated by Django 3.1.7 on 2021-07-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_accept_alteration'),
        ('authentication', '0009_auto_20210716_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neck_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.necksize'),
        ),
    ]
