# Generated by Django 3.1.7 on 2021-07-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210716_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neck_size',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
