# Generated by Django 3.1.7 on 2021-07-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_accept_alteration'),
        ('authentication', '0011_auto_20210716_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neck_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='necksize',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.necksize'),
        ),
    ]
