# Generated by Django 3.1.7 on 2021-07-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210716_0429'),
        ('authentication', '0012_auto_20210716_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
