# Generated by Django 3.1.7 on 2021-07-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='necksize',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
    ]
